name: Publish release

on:
  release:
    types:
      - published #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

jobs:
  build-and-test:
    runs-on: macos-latest
    env:
      DISABLE_TENCENT_MAVEN_MIRROR: true
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: revert gradle wrapper mirror setting
        run: echo 'distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip' >  gradle/wrapper/gradle-wrapper.properties
      - name: buildSdk
        run: ./gradlew buildSdk
      - name: build sample/source
        run: ./gradlew build
      - name: unit test
        run: ./gradlew jvmTestSdk -S
      - name: run androidTestSdk on API 28 emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          emulator-build: 7425822
          target: default
          arch: x86_64
          profile: pixel_xl
          script: ./gradlew androidTestSdk
      - name: stop gradle deamon for actions/cache
        run: ./gradlew --stop
  publish:
    needs: build-and-test
    runs-on: macos-latest
    env:
      DISABLE_TENCENT_MAVEN_MIRROR: true
      PUBLISH_RELEASE: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: revert gradle wrapper mirror setting
        run: echo 'distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip' >  gradle/wrapper/gradle-wrapper.properties
      - name: publish
        run: ./gradlew publish
      - name: stop gradle deamon for actions/cache
        run: ./gradlew --stop
